org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# 拉长超时，弱网更稳
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000

# 若之前配过代理导致更慢，这里明确不用系统代理拉依赖
# （Android Studio 里请改回 No proxy）
systemProp.java.net.useSystemProxies=false
